### ISSUE TITLE
Adding a requirements.txt file

### ISSUE THREAD

**Issue by varunp2k** [varunp2k/WhatsappAutomation#7]

**Comment by dipanshu231099** [comment]
@varunp2k i would like to do it kindly tell what to do exactly

**Comment by Samyak2** [comment]
requirements.txt must contain a list of all python packages required along with their version. In this format:
```
selenium==3.141.0
```
You can also use >= instead of ==
Also, add the webdrivers (chromedriver or geckodriver) required by selenium in the README file, links to those should suffice.

**Comment by varunp2k** [comment]
Go through the code.
There are a few packages which need to be explicitly installed
