### ISSUE TITLE
Replace explicit waits

### ISSUE THREAD

**Issue by Samyak2** [varunp2k/WhatsappAutomation#9]
## The issue

 - `time.sleep()` along with try-except is being used whenever clicking an element fails.
 - If the click fails a second time (after waiting for 1 second), it will raise an exception and exit.

## The solution

 - Use `WebDriverWait` with expected conditions to click or get elements.
 - Check [this comment](https://github.com/varunp2k/WhatsappAutomation/issues/2#issuecomment-537161047) for an example.
 - `WebDriverWait` could also be used to automate the process of continuing after scanning the QR code, so that the user no longer has to press enter after scanning the code.

**Comment by lpraz** [comment]
Can I work on this issue?

**Comment by varunp2k** [comment]
Sure.
